/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Homepage: typeof import('./src/components/homepage/homepage.vue')['default']
    Idcard: typeof import('./src/components/idcard/idcard.vue')['default']
    Login: typeof import('./src/components/login/login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test/test.vue')['default']
  }
}
